stages:
  - test
  - report

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  ALLURE_RESULTS: "target/allure-results"

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  image: maven:3.8.6-amazoncorretto-17  # Специальный образ с Maven + Corretto
  script:
    - mvn --version
    - mvn clean test
  artifacts:
    when: always
    paths:
      - target/allure-results/
    expire_in: 1 week

generate-report:
  stage: report
  image: maven:3.8.6-amazoncorretto-17
  needs: ["test"]
  script:
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - target/site/allure-maven-plugin/
    expose_as: "Allure Report"