name: API Tests for External Project

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Launch external API
        run: |
          git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git external_api
          cd external_api
          sudo docker compose up --build -d
          
          # Улучшенная проверка готовности API
          for i in {1..30}; do
            if curl -s http://localhost:8080/api/getall >/dev/null; then
              echo "API is ready!"
              break
            fi
            echo "Waiting for API to start... ($i/30)"
            sleep 5
          done

      - name: Verify API status
        run: |
          curl -f http://localhost:8080/api/getall || (echo "API failed to start"; exit 1)

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run tests with Allure
        run: |
          mvn clean test
          mkdir -p allure-results
          [ -d target/allure-results ] && cp -r target/allure-results/* allure-results/

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.ref_name }}
          path: allure-results/
          retention-days: 1

      - name: Clean up
        if: always()
        run: |
          cd external_api && sudo docker compose down -v || true
          sudo docker system prune -a -f || true