name: Запуск API тестов для проекта

on:
  push:
    branches: [ 'main' ]  # Запускаем только для main ветки
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код проекта
        uses: actions/checkout@v4

      - name: Установить Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Установить Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo docker --version
          sudo docker-compose --version

      - name: Запустить внешний API
        run: |
          # Клонируем репозиторий с API
          git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git external_api
          cd external_api
          
          # Запускаем сервисы в фоне
          sudo docker-compose up --build -d
          
          # Ждем пока API станет доступным (максимум 2 минуты)
          echo "Ожидание запуска API..."
          for i in {1..12}; do
            if curl -s http://localhost:8080/api/getAll >/dev/null; then
              echo "API успешно запущен!"
              break
            fi
            echo "Попытка $i/12 - API еще не готов..."
            sleep 10
          done

      - name: Проверить статус API
        run: |
          curl -f http://localhost:8080/api/getAll || (echo "Ошибка: API не запустился"; exit 1)

      - name: Запустить тесты
        run: |
          mvn -B clean test
          mvn allure:report

      - name: Сохранить Allure отчет
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
          retention-days: 3

      - name: Остановить сервисы
        if: always()
        run: |
          cd external_api && sudo docker-compose down -v
          sudo docker system prune -a -f