name: Java CI with Maven and Allure

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      api-server:
        image: simbirsoft_sdet_project-service:latest
        ports:
          - 8080:8080
        options: >-
          --health-cmd "curl -f http://localhost:8080/api/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          -e SPRING_PROFILES_ACTIVE=test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run tests
        run: mvn -B test
        env:
          API_BASE_URL: http://localhost:8080/api

      - name: Generate Allure Report
        if: always()
        run: |
          mvn allure:report
          mkdir -p allure-report
          cp -R target/site/allure-maven-plugin/* allure-report/

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 5